name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair:
          - otp-version: '26.0'
            elixir-version: '1.16.0'
          - otp-version: '27.3.3'
            elixir-version: '1.18.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp-version}}
          elixir-version: ${{matrix.pair.elixir-version}}
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests with espec
        run: mix espec
      - name: cd to rumbrella
        run: cd rumbrella
      - name: Install rumbrella deps
        run: mix deps.get
      - name: Run mix test
        run: mix test
      - name: Run mix espec
        run: mix espec

